#!/usr/bin/env bash
set -euo pipefail
skill_root="$(cd "$(dirname "$0")/.." && pwd)"
node --input-type=module - "$skill_root" <<'JS'
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.argv[2];const required=['SKILL.md','assets/root/AGENTS.md','assets/harness/cli','assets/harness/root.json','assets/harness/project.json','assets/harness/check.mjs','assets/harness/wiki.mjs','assets/harness/core/task-cli.mjs','assets/harness/adapter-capabilities.json','assets/wiki-reader/index.html','assets/wiki-reader/reader.js','assets/wiki-reader/manifest.json','scripts/harness-manager.mjs','migration/legacy.mjs'];
for(const f of required)assert.ok(fs.existsSync(path.join(root,f)),'Missing '+f);
const names=['lumine-design','lumine-knowledge','lumine-plan','lumine-run'];assert.deepEqual(fs.readdirSync(path.join(root,'assets/skills')).filter(n=>!n.startsWith('.')).sort(),names);
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):e.isFile()?[path.join(dir,e.name)]:[]);}
for(const name of names){for(const locale of ['zh-CN','en']){const base=locale==='en'?path.join(root,'assets/locales/en/skills',name):path.join(root,'assets/skills',name);const entry=path.join(base,locale==='en'?'SKILL.md.template':'SKILL.md');assert.ok(fs.existsSync(entry));const text=fs.readFileSync(entry,'utf8');assert.ok(text.includes('name: '+name));assert.match(text,/description:/);for(const f of files(base)){const body=fs.readFileSync(f,'utf8');assert.doesNotMatch(body,/\.harness[\/`]|lumine-harness-(?:draft|plan|run|generated|navigate|design|check)|docs\/drafts|docs\/generated/,'Legacy instructions in '+f);assert.doesNotMatch(body,/\/(?:Users|home)\/[^/\s]+\//,'Private path in '+f);}}}
for(const f of files(path.join(root,'assets/harness')).filter(f=>f.endsWith('.mjs'))){const text=fs.readFileSync(f,'utf8');assert.ok(text.includes('@generated by pnpm runtime:build'),'Non-generated runtime '+f);assert.doesNotMatch(text,/(?:from\s*|import\()["'][^"']+\.ts["']/,'TS import in distribution '+f);}
for(const product of ['codex','trae','qoder','cursor','codebuddy']){const f=path.join(root,'assets',product,product==='qoder'||product==='codebuddy'?'settings.json':'hooks.json');assert.ok(fs.existsSync(f));assert.doesNotMatch(fs.readFileSync(f,'utf8'),/\.harness\//);}
const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/harness/adapter-capabilities.json'),'utf8'));assert.equal(manifest.schemaVersion,4);assert.equal(manifest.skillSource,'.agents/skills');
for(const p of ['codex','trae','qoder','kimi','cursor','opencode','zcode','codebuddy','deepseek-harness'])assert.ok(manifest.products[p]);
for(const dir of ['assets/qoder/skills','assets/trae/skills','assets/cursor/rules','assets/codebuddy/skills'])assert.ok(!fs.existsSync(path.join(root,dir)),'Product Skill copies are forbidden');
console.log('Four bilingual Skills, runtime, offline reader, migration boundary and adapters verified.');
JS
