#!/usr/bin/env node
// @generated by pnpm runtime:build from TypeScript source; do not edit directly.
// Source: skills/lumine-harness/src/scripts/harness-manager.ts
import { isMainModule, loadNodeMain, unavailableNodeRuntime } from "../assets/harness/core/node-bootstrap.mjs";
const implementation = await loadNodeMain(() => import("./harness-manager-main.mjs"), { entryUrl: import.meta.url });
const inspectTarget = implementation ? implementation.inspectTarget : unavailableNodeRuntime;
const createProposal = implementation ? implementation.createProposal : unavailableNodeRuntime;
const applyProposal = implementation ? implementation.applyProposal : unavailableNodeRuntime;
const rollbackProposal = implementation ? implementation.rollbackProposal : unavailableNodeRuntime;
const finalizeProposal = implementation ? implementation.finalizeProposal : unavailableNodeRuntime;
if (implementation && isMainModule(import.meta.url)) await implementation.runManagerCli();
export {
  applyProposal,
  createProposal,
  finalizeProposal,
  inspectTarget,
  rollbackProposal
};
