import { spawnSync } from "node:child_process";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync
} from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runtimeArtifacts, type RuntimeArtifact } from "./runtime-artifacts.ts";

const GENERATED_MARKER = "// @generated by pnpm runtime:build from TypeScript source; do not edit directly.";
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = path.join(repoRoot, "skills/lumine-harness/src");

function run(command: string, args: string[], env: NodeJS.ProcessEnv): void {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    env,
    encoding: "utf8",
    stdio: "inherit"
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} exited with status ${result.status ?? "unknown"}`);
  }
}

function addGeneratedMarker(content: string, source: string): string {
  const marker = `${GENERATED_MARKER}\n// Source: skills/lumine-harness/src/${source}\n`;
  if (content.startsWith("#!")) {
    const newline = content.indexOf("\n");
    return `${content.slice(0, newline + 1)}${marker}${content.slice(newline + 1)}`;
  }
  return `${marker}${content}`;
}

function artifactContent(artifact: RuntimeArtifact, stageRoot: string): string {
  let content: string;
  if (artifact.stage) {
    const stageFile = path.join(stageRoot, artifact.stage);
    if (!existsSync(stageFile)) throw new Error(`Missing staged artifact: ${artifact.stage}`);
    content = readFileSync(stageFile, "utf8");
  } else {
    content = readFileSync(path.join(sourceRoot, artifact.source), "utf8");
  }
  if (artifact.transform) content = artifact.transform(content);
  return addGeneratedMarker(content, artifact.source);
}

function collectPublicRuntimeFiles(root: string): string[] {
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true })
    .flatMap((entry) => {
      const absolute = path.join(root, entry.name);
      if (entry.isDirectory()) return collectPublicRuntimeFiles(absolute);
      return entry.isFile() && (entry.name.endsWith(".mjs") || entry.name === "contracts.d.ts")
        ? [path.relative(repoRoot, absolute)]
        : [];
    })
    .sort();
}

function assertManifestCoversPublicRuntime(artifacts: RuntimeArtifact[]): void {
  const expected = new Set(artifacts.map((artifact) => artifact.destination));
  const actual = [
    ...collectPublicRuntimeFiles(path.join(repoRoot, "skills/lumine-harness/assets/harness")),
    ...collectPublicRuntimeFiles(path.join(repoRoot, "skills/lumine-harness/assets/opencode/plugins")),
    path.join("skills/lumine-harness/scripts/harness-manager.mjs")
  ].sort();
  const unmanaged = actual.filter((file) => !expected.has(file));
  if (unmanaged.length > 0) {
    throw new Error(`Runtime manifest does not cover:\n${unmanaged.join("\n")}`);
  }
}

function synchronize(mode: "write" | "check", stageRoot: string): void {
  const artifacts = runtimeArtifacts(repoRoot);
  assertManifestCoversPublicRuntime(artifacts);
  const drift: string[] = [];

  for (const artifact of artifacts) {
    const destination = path.join(repoRoot, artifact.destination);
    const expected = artifactContent(artifact, stageRoot);
    const actual = existsSync(destination) ? readFileSync(destination, "utf8") : null;
    if (actual === expected) continue;
    if (mode === "check") {
      drift.push(artifact.destination);
      continue;
    }
    mkdirSync(path.dirname(destination), { recursive: true });
    writeFileSync(destination, expected);
    if (artifact.executable) chmodSync(destination, 0o755);
  }

  if (drift.length > 0) {
    throw new Error(`Generated runtime artifacts are stale:\n${drift.join("\n")}\nRun pnpm runtime:build.`);
  }
}

function main(): void {
  const mode = process.argv.includes("--check") ? "check" : process.argv.includes("--write") ? "write" : null;
  if (!mode) throw new Error("Usage: tsx scripts/build-runtime.ts --write|--check");

  const tempRoot = mkdtempSync(path.join(os.tmpdir(), "lumine-harness-runtime-"));
  const stageRoot = path.join(tempRoot, "stage");
  try {
    run("pnpm", ["exec", "tsdown", "--config", "tsdown.config.ts"], {
      ...process.env,
      LUMINE_RUNTIME_STAGE: stageRoot
    });
    synchronize(mode, stageRoot);
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
}

main();
