import { build } from "esbuild";
import { spawnSync } from "node:child_process";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runtimeArtifacts, type RuntimeArtifact } from "./runtime-artifacts.ts";
import { synchronizeHookConfigs } from "./build-hook-configs.ts";
import { SUPPORTED_NODE_ENGINES, assertNodeRuntime } from "../skills/lumine-harness/src/harness/core/node-runtime.ts";

const GENERATED_MARKER =
  "// @generated by pnpm runtime:build from TypeScript source; do not edit directly.";
const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const sourceRoot = path.join(repoRoot, "skills/lumine-harness/src");

function run(command: string, args: string[], env: NodeJS.ProcessEnv): void {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    env,
    encoding: "utf8",
    stdio: "inherit",
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(
      `${command} ${args.join(" ")} exited with status ${result.status ?? "unknown"}`,
    );
  }
}

function addGeneratedMarker(content: string, source: string): string {
  const marker = `${GENERATED_MARKER}\n// Source: skills/lumine-harness/src/${source}\n`;
  if (content.startsWith("#!")) {
    const newline = content.indexOf("\n");
    return `${content.slice(0, newline + 1)}${marker}${content.slice(newline + 1)}`;
  }
  return `${marker}${content}`;
}

function artifactContent(artifact: RuntimeArtifact, stageRoot: string): string {
  let content: string;
  if (artifact.stage) {
    const stageFile = path.join(stageRoot, artifact.stage);
    if (!existsSync(stageFile))
      throw new Error(`Missing staged artifact: ${artifact.stage}`);
    content = readFileSync(stageFile, "utf8");
  } else {
    content = readFileSync(path.join(sourceRoot, artifact.source), "utf8");
  }
  if (artifact.bootstrap) content = content.replace(/(["'])(\.{1,2}\/[^"']+)\.ts\1/g, "$1$2.mjs$1");
  if (artifact.transform) content = artifact.transform(content);
  for (const dependency of ["yaml", "ignore"]) {
    if (artifact.source === `harness/vendor/${dependency}.ts`) continue;
    let vendor = path
      .relative(
        path.dirname(artifact.destination),
        `skills/lumine-harness/assets/harness/vendor/${dependency}.mjs`,
      )
      .split(path.sep)
      .join("/");
    if (!vendor.startsWith(".")) vendor = "./" + vendor;
    content = content.replace(
      new RegExp(`from ["']${dependency}["']`, "g"),
      `from "${vendor}"`,
    );
  }
  return addGeneratedMarker(content, artifact.source);
}

function collectPublicRuntimeFiles(root: string): string[] {
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true })
    .flatMap((entry) => {
      const absolute = path.join(root, entry.name);
      if (entry.isDirectory()) return collectPublicRuntimeFiles(absolute);
      return entry.isFile() &&
        (entry.name.endsWith(".mjs") || entry.name === "contracts.d.ts")
        ? [path.relative(repoRoot, absolute)]
        : [];
    })
    .sort();
}

function assertManifestCoversPublicRuntime(artifacts: RuntimeArtifact[], mode: "write" | "check"): void {
  const expected = new Set(artifacts.map((artifact) => artifact.destination));
  const actual = [
    ...collectPublicRuntimeFiles(
      path.join(repoRoot, "skills/lumine-harness/assets/harness"),
    ),
    ...collectPublicRuntimeFiles(
      path.join(repoRoot, "skills/lumine-harness/assets/opencode/plugins"),
    ),
    ...collectPublicRuntimeFiles(path.join(repoRoot, "skills/lumine-harness/scripts")),
    ...collectPublicRuntimeFiles(path.join(repoRoot, "skills/lumine-harness/migration")),
  ].sort();
  const unmanaged = actual.filter((file) => !expected.has(file)).filter((file) => {
    if (mode !== "write") return true;
    const content = readFileSync(path.join(repoRoot, file), "utf8");
    const retired = /^\/\/ Source: skills\/lumine-harness\/src\/([^\n]+)$/m.exec(content)?.[1];
    // Only retire generated output whose canonical source was removed.
    // Unknown files and outputs with an extant source still fail the manifest gate.
    if (!content.includes(GENERATED_MARKER) || !retired || retired.includes("..") || existsSync(path.join(sourceRoot, retired))) return true;
    rmSync(path.join(repoRoot, file));
    return false;
  });
  if (unmanaged.length > 0) {
    throw new Error(
      `Runtime manifest does not cover:\n${unmanaged.join("\n")}`,
    );
  }
}

function synchronize(mode: "write" | "check", stageRoot: string): void {
  const artifacts = runtimeArtifacts(repoRoot);
  assertManifestCoversPublicRuntime(artifacts, mode);
  const drift: string[] = [];

  for (const artifact of artifacts) {
    const destination = path.join(repoRoot, artifact.destination);
    const expected = artifactContent(artifact, stageRoot);
    const actual = existsSync(destination)
      ? readFileSync(destination, "utf8")
      : null;
    if (actual === expected) continue;
    if (mode === "check") {
      drift.push(artifact.destination);
      continue;
    }
    mkdirSync(path.dirname(destination), { recursive: true });
    writeFileSync(destination, expected);
    if (artifact.executable) chmodSync(destination, 0o755);
  }

  if (drift.length > 0) {
    throw new Error(
      `Generated runtime artifacts are stale:\n${drift.join("\n")}\nRun pnpm runtime:build.`,
    );
  }
}

async function main(): Promise<void> {
  assertNodeRuntime(process.versions.node);
  const pkg = JSON.parse(readFileSync(path.join(repoRoot, "package.json"), "utf8"));
  if (pkg.engines?.node !== SUPPORTED_NODE_ENGINES) throw new Error("package.json Node engines differ from the shared runtime policy.");
  const mode = process.argv.includes("--check")
    ? "check"
    : process.argv.includes("--write")
      ? "write"
      : null;
  if (!mode)
    throw new Error("Usage: tsx scripts/build-runtime.ts --write|--check");

  const tempRoot = mkdtempSync(
    path.join(os.tmpdir(), "lumine-harness-runtime-"),
  );
  const stageRoot = path.join(tempRoot, "stage");
  try {
    run("pnpm", ["exec", "tsdown", "--config", "tsdown.config.ts"], {
      ...process.env,
      LUMINE_RUNTIME_STAGE: stageRoot,
    });
    for (const dependency of ["yaml", "ignore"])
      await build({
        entryPoints: [path.join(sourceRoot, `harness/vendor/${dependency}.ts`)],
        outfile: path.join(stageRoot, `harness/vendor/${dependency}.mjs`),
        bundle: true,
        format: "esm",
        platform: "node",
        target: "node22",
        banner: {
          js: 'import { createRequire as vendorCreateRequire } from "node:module"; const require = vendorCreateRequire(import.meta.url);',
        },
        legalComments: "inline",
      });
    // Rebuild only launchers and their pure prerequisites with old syntax.
    // The implementation remains node22; dispatchers copied on their own bundle the guard.
    for (const artifact of runtimeArtifacts(repoRoot).filter((item) => item.bootstrap)) {
      await build({ entryPoints: [path.join(sourceRoot, artifact.source)],
        outfile: path.join(stageRoot, artifact.stage!), bundle: artifact.bundle ?? false,
        format: "esm", platform: "node", target: "node18", legalComments: "inline" });
    }
    const licensePath = path.join(
      repoRoot,
      "skills/lumine-harness/assets/harness/THIRD-PARTY-LICENSES.txt",
    );
    const serverLicenses = ["yaml", "ignore"]
      .map((name) => {
        const directory = path.join(repoRoot, "node_modules", name);
        const pkg = JSON.parse(
          readFileSync(path.join(directory, "package.json"), "utf8"),
        );
        const files = readdirSync(directory).filter((file) =>
          /^(license|licence|copying|notice)(\.|$)/i.test(file),
        );
        return (
          `${pkg.name}@${pkg.version} (${pkg.license})\n` +
          files
            .map((file) => readFileSync(path.join(directory, file), "utf8"))
            .join("\n")
        );
      })
      .join("\n\n");
    if (mode === "write") writeFileSync(licensePath, serverLicenses);
    else if (
      !existsSync(licensePath) ||
      readFileSync(licensePath, "utf8") !== serverLicenses
    )
      throw new Error("Server dependency licenses are stale");
    synchronize(mode, stageRoot);
    await synchronizeHookConfigs(repoRoot, mode);
    run(
      "pnpm",
      [
        "exec",
        "tsx",
        "scripts/build-reader.ts",
        mode === "write" ? "--write" : "--check",
      ],
      process.env,
    );
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
