// @generated by pnpm runtime:build from TypeScript source; do not edit directly.
// Source: skills/lumine-harness/src/migration/legacy.ts
import { getSessionStatePath } from "../assets/harness/core/work-status.mjs";
import path from "node:path";
import { copyFileSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, rmdirSync } from "node:fs";
import { createHash } from "node:crypto";

//#region skills/lumine-harness/src/migration/legacy.ts
const oldRoot = ".harness";
const names = [
	"navigate",
	"draft",
	"generated",
	"design",
	"plan",
	"run",
	"check"
];
const products = new Set([
	"codex",
	"qoder",
	"trae",
	"kimi",
	"cursor",
	"opencode",
	"zcode",
	"codebuddy",
	"deepseek-harness"
]);
const retiredTemplates = [
	"draft.md",
	"component-map.md",
	"handoff.md",
	"handoff.design.json"
];
const protocolFiles = new Set([
	".harness/project.json",
	".harness/root.json",
	".harness/managed.json"
]);
const read = (file) => JSON.parse(readFileSync(file, "utf8"));
const slash = (value) => value.split(path.sep).join("/");
const digest = (value) => createHash("sha256").update(value).digest("hex");
const present = (file) => {
	try {
		lstatSync(file);
		return true;
	} catch {
		return false;
	}
};
function safePath(root, relative) {
	if (path.isAbsolute(relative) || relative.includes("\\") || relative.split("/").includes("..")) throw new Error("Unsafe legacy path: " + relative);
	const file = path.resolve(root, relative);
	if (!file.startsWith(path.resolve(root) + path.sep)) throw new Error("Legacy path outside project");
	for (let current = file; current !== path.resolve(root); current = path.dirname(current)) {
		if (present(current) && lstatSync(current).isSymbolicLink()) throw new Error("Legacy symlink protected: " + relative);
	}
	return file;
}
/** Never descend into symlinks, private local trees, or embedded repositories. */
function inventory(root, relative, protectLocal = true) {
	const result = {
		files: [],
		protectedPaths: []
	};
	const visit = (rel) => {
		const file = path.join(root, rel);
		if (!present(file)) return;
		const info = lstatSync(file);
		if (info.isSymbolicLink() || !info.isFile() && !info.isDirectory()) {
			result.protectedPaths.push(rel);
			return;
		}
		if (info.isFile()) {
			result.files.push(rel);
			return;
		}
		const entries = readdirSync(file, { withFileTypes: true });
		if (!entries.length) return;
		if (present(path.join(file, ".git")) || protectLocal && rel === ".harness/local") {
			result.protectedPaths.push(rel);
			return;
		}
		for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) visit(slash(path.join(rel, entry.name)));
	};
	visit(relative);
	return result;
}
function managedFiles(root) {
	const file = safePath(root, ".harness/managed.json");
	return existsSync(file) ? read(file).files ?? {} : {};
}
function inspectLegacy(root) {
	const file = safePath(root, ".harness/project.json");
	return {
		exists: existsSync(file),
		project: existsSync(file) ? read(file) : {},
		managed: managedFiles(root)
	};
}
function convertLegacyProject(current, children) {
	const { generatedTargets, childRepositories, ...rest } = current;
	return {
		...rest,
		modules: (current.modules ?? ["workflow"]).filter((module) => module !== "generated"),
		repositories: current.repositories ?? [{
			id: "project",
			path: "."
		}, ...(childRepositories ?? children).map((relative) => ({
			id: relative.replace(/[^a-zA-Z0-9_-]/g, "-"),
			path: relative
		}))],
		autonomy: current.autonomy ?? {
			maxContinuationChain: 20,
			noProgressThreshold: 2
		},
		extensions: { ...current.extensions }
	};
}
function retirementAssessment(root, reviewedPaths) {
	const managed = managedFiles(root), reviewed = new Set(reviewedPaths), paths = [], conflicts = [];
	const inventories = names.map((name) => inventory(root, ".agents/skills/lumine-harness-" + name, false));
	for (const name of retiredTemplates) inventories.push(inventory(root, "docs/templates/" + name, false));
	for (const item of inventories) {
		conflicts.push(...item.protectedPaths);
		for (const relative of item.files) {
			if (reviewed.has(relative) || managed[relative]?.hash === digest(readFileSync(safePath(root, relative)))) paths.push(relative);
			else conflicts.push(relative);
		}
	}
	return {
		paths: [...new Set(paths)].sort(),
		conflicts: [...new Set(conflicts)].sort()
	};
}
/** Deletions enter the manager's ordinary journal and backup flow. */
function legacyRetirements(root, reviewedPaths = []) {
	return retirementAssessment(root, reviewedPaths).paths;
}
function legacyRetirementConflicts(root, reviewedPaths = []) {
	return retirementAssessment(root, reviewedPaths).conflicts;
}
function convertLegacySessions(root) {
	const result = new Map();
	const candidates = new Map();
	const archive = (relative, original) => {
		result.set(slash(path.join(".lumine/local/migration-history/runtime", path.relative(".harness/runtime", relative))), original);
	};
	for (const relative of inventory(root, ".harness/runtime").files) {
		const bytes = readFileSync(safePath(root, relative));
		const original = bytes.toString("utf8");
		if (!Buffer.from(original).equals(bytes)) continue;
		let value;
		try {
			value = JSON.parse(original);
		} catch {
			archive(relative, original);
			continue;
		}
		if (!relative.startsWith(".harness/runtime/sessions/") || !value || typeof value !== "object" || Array.isArray(value) || !products.has(value.product) || typeof value.sessionId !== "string" || !value.sessionId.trim() || value.sessionId === "unknown") {
			archive(relative, original);
			continue;
		}
		const destination = slash(path.relative(root, getSessionStatePath(root, value.product, value.sessionId)));
		const entries = candidates.get(destination) ?? [];
		entries.push({
			relative,
			original,
			value
		});
		candidates.set(destination, entries);
	}
	for (const [destination, entries] of candidates) {
		if (entries.length !== 1) {
			for (const entry of entries) archive(entry.relative, entry.original);
			continue;
		}
		const { relative, original, value } = entries[0];
		archive(relative, original);
		for (const key of [
			"expectedSkill",
			"expectedSkillPath",
			"expectedSkillRead",
			"expectedSkillReadAt",
			"expectedPhase",
			"expectedSkills",
			"taskUserTurnRevision"
		]) delete value[key];
		Object.assign(value, {
			schemaVersion: 2,
			expectedSkills: [],
			usedSkills: [],
			selectedSkills: [],
			skillCandidates: [],
			expectedSkillRead: false,
			requestedActivity: null,
			pendingContinuationRequestId: null,
			pendingContinuationRevision: null,
			continuationRequestedAt: null,
			continuationDeliveredAt: null
		});
		result.set(destination, JSON.stringify(value, null, 2) + "\n");
	}
	return result;
}
function legacyTransition(root, adapters, reviewedPaths = []) {
	const before = {}, bridges = {};
	const scan = inventory(root, oldRoot), protectedPaths = [...scan.protectedPaths];
	const managed = managedFiles(root), reviewed = new Set(reviewedPaths);
	for (const relative of scan.files) {
		const file = safePath(root, relative), bytes = readFileSync(file), fingerprint = digest(bytes);
		const recoverableState = relative.startsWith(".harness/runtime/") && /\.jsonl?$/.test(relative) && Buffer.from(bytes.toString("utf8")).equals(bytes);
		const known = protocolFiles.has(relative) || recoverableState || managed[relative]?.hash === fingerprint || reviewed.has(relative);
		if (!known) {
			protectedPaths.push(relative);
			continue;
		}
		before[relative] = fingerprint;
		if (relative === oldRoot + "/cli") {
			bridges[relative] = "#!/usr/bin/env bash\nset -euo pipefail\nexec \"$(cd \"$(dirname \"$0\")/../.lumine\" && pwd)/cli\" \"$@\"\n";
		} else if (adapters.some((adapter) => relative.startsWith(oldRoot + "/adapters/" + adapter + "/hooks/")) && relative.endsWith(".mjs") && !relative.includes("/lib/")) {
			const destination = path.join(root, ".lumine", path.relative(path.join(root, oldRoot), file));
			const modulePath = slash(path.relative(path.dirname(file), destination));
			bridges[relative] = "// Temporary migration bridge; removed after host verification.\n" + "import { spawnSync } from 'node:child_process';\nimport { fileURLToPath } from 'node:url';\n" + `const entry = fileURLToPath(new URL(${JSON.stringify(modulePath)}, import.meta.url));\n` + "const result = spawnSync(process.execPath, [entry, ...process.argv.slice(2)], { stdio: 'inherit' });\n" + "if (result.error) { process.stderr.write(result.error.message + '\\n'); process.exit(1); }\n" + "if (result.signal) { process.kill(process.pid, result.signal); } else { process.exit(result.status ?? 1); }\n";
		}
	}
	return {
		before,
		bridges,
		protectedPaths: [...new Set(protectedPaths)].sort()
	};
}
function backupLegacy(root, recovery, snapshot) {
	for (const [relative, expected] of Object.entries(snapshot)) {
		const source = safePath(root, relative), destination = safePath(recovery, "legacy/" + relative);
		if (existsSync(destination)) {
			if (digest(readFileSync(destination)) !== expected) throw new Error("Legacy backup changed: " + relative);
			continue;
		}
		if (!existsSync(source) || digest(readFileSync(source)) !== expected) throw new Error("Legacy input changed: " + relative);
		mkdirSync(path.dirname(destination), {
			recursive: true,
			mode: 448
		});
		copyFileSync(source, destination);
	}
}
function finishLegacy(root, recovery, snapshot, bridges, protectedPaths = []) {
	const current = inventory(root, oldRoot);
	const unexpected = current.files.filter((relative) => !Object.hasOwn(snapshot, relative));
	const blocked = [...new Set([
		...protectedPaths.filter((relative) => present(path.join(root, relative))),
		...current.protectedPaths,
		...unexpected
	])];
	if (blocked.length) throw new Error("Protected legacy content remains; preserved for review: " + blocked.join(", "));
	for (const [relative, expected] of Object.entries(snapshot)) {
		const file = safePath(root, relative), backup = safePath(recovery, "legacy/" + relative);
		if (!existsSync(backup) || digest(readFileSync(backup)) !== expected) throw new Error("Missing verified backup: " + relative);
		if (existsSync(file) && digest(readFileSync(file)) !== (bridges[relative] ? digest(Buffer.from(bridges[relative])) : expected)) throw new Error("Legacy file changed; preserve and review: " + relative);
	}
	for (const relative of Object.keys(snapshot)) {
		const file = safePath(root, relative);
		if (existsSync(file)) rmSync(file);
	}
	const prune = (directory) => {
		if (!present(directory) || lstatSync(directory).isSymbolicLink()) return;
		for (const entry of readdirSync(directory, { withFileTypes: true })) if (entry.isDirectory()) prune(path.join(directory, entry.name));
		if (!readdirSync(directory).length) rmdirSync(directory);
	};
	prune(path.join(root, oldRoot));
	if (existsSync(path.join(root, oldRoot))) throw new Error("Unclassified legacy files remain; preserved for review.");
}
function restoreLegacy(root, recovery, snapshot, bridges) {
	const conflicts = [];
	for (const [relative, expected] of Object.entries(snapshot)) {
		try {
			const file = safePath(root, relative), backup = safePath(recovery, "legacy/" + relative);
			if (!existsSync(backup) || digest(readFileSync(backup)) !== expected) {
				conflicts.push(relative);
				continue;
			}
			if (existsSync(file)) {
				const actual = digest(readFileSync(file));
				if (actual === expected) continue;
				if (!bridges[relative] || actual !== digest(Buffer.from(bridges[relative]))) {
					conflicts.push(relative);
					continue;
				}
			}
			mkdirSync(path.dirname(file), { recursive: true });
			copyFileSync(backup, file);
		} catch {
			conflicts.push(relative);
		}
	}
	return conflicts;
}
function pruneRetiredSkillDirectories(root) {
	for (const name of names) {
		const directory = safePath(root, ".agents/skills/lumine-harness-" + name);
		if (!existsSync(directory) || lstatSync(directory).isSymbolicLink()) continue;
		const prune = (current) => {
			for (const entry of readdirSync(current, { withFileTypes: true })) if (entry.isDirectory() && !entry.isSymbolicLink()) prune(path.join(current, entry.name));
			if (!readdirSync(current).length) rmdirSync(current);
		};
		prune(directory);
	}
}

//#endregion
export { backupLegacy, convertLegacyProject, convertLegacySessions, finishLegacy, inspectLegacy, legacyRetirementConflicts, legacyRetirements, legacyTransition, pruneRetiredSkillDirectories, restoreLegacy };